# Generated by Django 5.2.7 on 2025-10-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='食材名稱')),
                ('quantity', models.IntegerField(default=0, verbose_name='數量')),
                ('unit', models.CharField(default='個', max_length=20, verbose_name='單位')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='到期日')),
                ('category', models.CharField(default='未分類', max_length=50, verbose_name='類別')),
                ('storage_location', models.CharField(default='冷藏', max_length=50, verbose_name='儲存位置')),
            ],
            options={
                'verbose_name': '食材',
                'verbose_name_plural': '食材管理',
            },
        ),
    ]
