# Generated by Django 5.2.7 on 2025-10-26 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(blank=True, max_length=100, verbose_name='產地')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('storage_instructions', models.TextField(blank=True, verbose_name='儲存說明')),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='food.ingredient', verbose_name='食材')),
            ],
            options={
                'verbose_name': '食材詳細資料',
                'verbose_name_plural': '食材詳細資料',
            },
        ),
    ]
